---
title: "p8105_hw1"
author: "Yueli Ma"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

```{r}
hw1_df = 
  tibble(
    sample = rnorm(10),
    gr_than_0 = sample>0,
    vec_char = c("a", "b", "c", "d", "e", "f","g", "h", "i", "j"),
    vec_factor = factor(c("one", "two", "three","one", "two", "three","one", "two", "three","one"))
  )
hw1_df
mean(pull(hw1_df,sample))
mean(pull(hw1_df,gr_than_0))
mean(pull(hw1_df,vec_char))
mean(pull(hw1_df,vec_factor))
```
##I found that only int and logical vector can be calculated mean value directly
```{r}
logic_to_numeric = as.numeric(pull(hw1_df,gr_than_0))
mean(logic_to_numeric)
char_to_numeric = as.numeric(pull(hw1_df,vec_char))
mean(char_to_numeric)
fac_to_numeric = as.numeric(pull(hw1_df,vec_factor))
mean(fac_to_numeric)
```
##When converted to numeric, logical vector can still be calculated the mean value and characters like "one", "two" can also be calculated. However, characters that do not mean any numbers cannot be converted and cannot be calculated

```{r }
data("penguins", package = "palmerpenguins")
penguins
summary(penguins)
nrow(penguins)
ncol(penguins)
mean(pull(penguins,flipper_length_mm),na.rm=TRUE)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species))+ geom_point()
ggsave("penguins.pdf", height = 4, width = 6)
```
